basic.forever(function on_forever() {
    basic.showIcon(IconNames.Heart)
    basic.clearScreen()
    basic.pause(500)
    basic.showIcon(IconNames.SmallHeart)
    basic.clearScreen()
    basic.pause(500)
    basic.showNumber(1)
    basic.showNumber(2)
    basic.pause(500)
})
